import "@workspace/ui/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from "../components/Layout/navbar";
import data from "../lib/data/feature-page.json";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = data.data.sections.find(
    (section) => section.__component === "sections.navbar",
  );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-7xl mx-auto h-full`}
      >
        <NavBar data={navData} />
        <main className="max-w-7xl mx-auto px-2 py-4">{children}</main>
      </body>
    </html>
  );
}
